import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from master_article_v2 import validate
S=[]
def sec(h,*p):S.append({'heading':h,'paragraphs':list(p)})
sec('A Raise Is a Business Decision, Not a Rescue Plan',
'A household can trim subscriptions only so many times. Higher compensation can create recurring room for saving, debt repayment and ordinary life, but an employer does not approve a raise because the employee’s rent rose. The case must connect expanded value, market position and the employer’s pay process to a specific request.',
'That distinction is not cold; it is useful. Personal need can motivate the conversation, while business evidence gives the manager material to defend it. A manager who agrees privately may still need a compensation committee, budget owner, HR partner or salary-band exception. Build a case that can travel through those rooms without you.',
'Do not wait until financial pressure makes every answer feel like an emergency. Compensation planning should begin months before a review cycle. Track changing responsibilities, outcomes, praise, credentials and market evidence as they occur. Memory favors recent visible work and often misses quiet improvements that prevented errors or saved colleagues time.',
'A raise request is different from asking for recognition. Praise, title, bonus, promotion and base salary solve different problems. Base pay compounds into later percentage increases and can affect retirement contributions, disability coverage and future offers. A one-time bonus may reward an exceptional period without changing the role’s ongoing price.',
'Start with the employment reality. Is pay controlled by a published scale, union agreement, civil-service grade, grant budget, company band or manager discretion? Are increases annual, promotion-based, market adjustments or off-cycle exceptions? Negotiating the wrong mechanism wastes evidence even when the underlying case is strong.',
'Define the requested outcome before scheduling the meeting. State a target base salary or defensible range, effective date, title or level if relevant, and acceptable alternatives. “I want more” gives no decision point. “Adjust base salary to $84,000 to reflect the expanded scope and market range” can be evaluated.',
'Timing cannot manufacture budget, but it can avoid preventable friction. Ask before budgets close, after measurable delivery and when the manager has enough time to sponsor the request. Do not ambush a routine one-to-one with a demand requiring research. Request a dedicated compensation discussion and share a concise agenda.',
'The opening photo shows a professional meeting because compensation changes are organizational decisions, not solitary affirmations. The goal is a clear, evidence-led discussion in which the employee understands constraints and the employer understands the retention and role-pricing issue.',
'A raise also changes the household system. Estimate after-tax pay, benefit deductions and the destination of each increment before approval. Otherwise lifestyle expansion can absorb the result. Income growth beats endless cutting only when the added cash is assigned to durable priorities as deliberately as any budget.',
'Approach negotiation without false certainty. Strong performance does not guarantee money, and one rejected request does not prove low value. The process should produce either improved compensation or specific information: decision maker, criteria, timeline, budget window and the external options available if the gap remains.' )
sec('Map the Job You Actually Perform',
'Job descriptions age quickly. Begin with the role currently performed, not the title printed at hiring. List recurring responsibilities, decisions, scope, stakeholders, systems, risk and people supported. Mark what was present at hire, what expanded and what belongs to a higher-level role in the employer’s own framework.',
'Distinguish more work from higher-value scope. A heavy inbox can show workload but not necessarily a more valuable job. Strong evidence includes ownership of a larger region, higher-risk decisions, complex clients, staff leadership, scarce technical work, cross-functional coordination or accountability for revenue, cost, compliance and service quality.',
'Use O*NET and employer job families to name skills accurately. External occupation descriptions can reveal standard tasks, knowledge and responsibility, while the internal leveling guide shows how this organization prices them. Neither source replaces actual work; together they prevent a vague “I do everything” claim.',
'Create a responsibility-change table with four columns: original duty, current duty, frequency and consequence. “Helped with reporting” is weak. “Own the monthly regulatory report for six business units, coordinate three data owners and resolve exceptions before submission” describes scope that a reviewer can compare.',
'Include invisible work only when its consequence is visible. Mentoring, documentation, incident prevention and process maintenance matter, but translate them into reduced ramp time, fewer escalations, continuity, audit readiness or capacity released. Do not invent a dollar value where no reliable link exists.',
'Separate temporary coverage from permanent expansion. Covering a manager for two weeks can support a spot bonus or recognition; performing the higher-level duties for nine months supports role reclassification. Record dates and whether the organization continued relying on the expanded scope after the emergency ended.',
'Collect the employer’s prior signals: performance ratings, written feedback, stretch assignments, succession discussions and requests to train others. Positive comments are not a salary formula, but they corroborate the claim that the role has changed and performance supports investment.',
'Identify dependencies and handoffs without threatening departure. A map of processes, clients and decisions shows the role’s organizational reach. The purpose is not to imply that only one person can operate the business. A responsible case shows durable contribution, documentation and leadership rather than hostage value.',
'Ask the manager to validate scope before arguing price. “Does this reflect the role you expect me to continue performing?” can reveal disagreement early. If the manager sees the role differently, resolve duties, title and expectations before presenting a market percentile as though role identity were settled.',
'Keep the map to one page for the meeting and retain detail as backup. A case that requires twenty minutes of explanation is hard for a manager to repeat. Use specific nouns, verbs and quantities, remove emotional adjectives and make expanded responsibility visible at a glance.' )
sec('Use Market Data as a Range, Not a Verdict',
'Market data creates a reference range, not an invoice. Match occupation, geography, industry, level and responsibility as closely as possible. A national average for a broad title can be less relevant than a local distribution for the actual occupation, particularly when one title covers junior and senior work.',
'The Bureau of Labor Statistics Occupational Employment and Wage Statistics program publishes wage estimates for about 830 occupations, with national, state, area and industry views. [[S1|Its salary-negotiation guide]] recommends examining percentiles because the spread shows more than one average.',
'BLS explains that education, experience, location and industry can affect where a worker belongs within the distribution. A median is not automatic entitlement, and the 90th percentile is not a sensible anchor merely because it is highest. Explain why the role’s scope and qualifications align with the selected part of the range.',
'Use several sources with transparent methods. Public wage statistics, posted salary ranges, credible recruiter conversations, internal bands where available and comparable offers can corroborate one another. Anonymous self-reported websites can provide clues, but sample, recency and job matching may be weak.',
'Normalize hourly and annual figures using actual schedule. A salary attached to sixty-hour weeks is not directly comparable with a forty-hour role. Include expected bonus, commission, overtime eligibility and required travel. Never convert a contingent maximum into guaranteed base pay.',
'Adjust old figures for time cautiously. General inflation is not the same as market movement for one occupation. BLS Employment Cost Index data can show broad compensation change, while current postings and internal ranges address the role more directly. Do not add consumer inflation mechanically to an old salary survey and call it market price.',
'Geographic differences need more than cost-of-living rhetoric. Employers may price by office, residence, labor market or a national remote band. Ask which policy applies. The employee’s personal housing cost is real but does not establish the company’s geographic pay method.',
'Build a range table showing source date, occupation, location, industry, percentile or level, and compensation components. Remove sources that cannot be matched. The remaining range may be wider than desired; that honesty is more persuasive than selecting only the number nearest the target.',
'Internal equity matters alongside external market. A manager may need to compare peers, tenure, performance and salary compression. Ask where the role sits in its band and what movement requires. Do not demand confidential colleague data; request the framework and objective placement criteria.',
'The target should fit all three: current scope, credible external range and internal mechanism. If the evidence supports a promotion rather than an in-band raise, name that. If base pay is already near the band ceiling, prepare alternatives or a level-change case rather than pretending the ceiling does not exist.' )
sec('Translate Work into Decision-Useful Evidence',
'A manager needs more than a list of completed tasks. Organize evidence around outcomes: revenue enabled, cost reduced, time released, defects prevented, risk lowered, customers retained, capacity expanded or service improved. Use the measure the organization already trusts rather than creating a private scorecard solely for negotiation.',
'Choose a baseline and comparison period. “Cut processing time” becomes stronger as “reduced median processing time from five days to three across 1,200 monthly cases after the workflow change.” Include source and period so a reviewer can reproduce the result.',
'Do not claim the whole team’s output. State personal contribution and dependencies: designed the process, led rollout, built analysis or coordinated implementation. Shared success can still justify a raise. Inflated attribution creates an integrity risk greater than the apparent numerical gain.',
'Quantify prevention carefully. A control that prevented likely losses may matter, but hypothetical savings are not cash. Use observed incident reduction, audit findings, downtime avoided under documented assumptions or risk exposure accepted by the business. Label estimates and ranges rather than presenting guesses as audited facts.',
'Include quality with speed. Faster work that increases error, complaints or burnout is not a clean gain. Pair throughput with defect rate, customer measure, compliance result or team capacity. Compensation cases improve when they show sustainable performance rather than a short sprint.',
'Create three evidence tiers. Tier one contains verified results tied closely to the employee. Tier two contains strong qualitative evidence such as executive feedback or high-stakes ownership. Tier three contains context and effort. Lead with tier one, use tier two for texture and keep tier three out unless asked.',
'A promotion case should demonstrate behavior at the next level over enough time to judge. One successful project can justify recognition; repeated higher-level decisions show sustained scope. Match examples to the employer’s competencies instead of using generic claims about leadership.',
'Use a compact case sheet: role change, three to five outcomes, market range, requested adjustment and future priorities. Attach detailed calculations only if needed. The mid-article photograph of professionals examining charts belongs here because this section turns work into evidence a compensation reviewer can inspect.',
'Ask a trusted person to red-team the case. Can they identify the request, verify each number and explain why current work differs from the original role? Remove jargon, confidential data and weak examples. A reviewer should understand the case without insider context.',
'Keep evidence current after the conversation. If approval takes a quarter, add new outcomes and update market postings without changing the narrative every week. A stable case with fresh corroboration is easier to sponsor than a constantly expanding archive.' )
sec('Enter the Employer’s Compensation Calendar',
'Compensation decisions often happen before employees hear about them. Annual review meetings may follow calibration, budget approval and leadership ranking. Ask when recommendations are due, who approves them and whether off-cycle adjustments exist. The best evidence arrives before the decision window closes.',
'Learn the difference among merit increase, market adjustment, equity correction, promotion increase, retention adjustment and bonus. Labels can determine budget source and approval standard. Describe the actual reason rather than forcing expanded scope into a small merit pool.',
'Request a dedicated meeting with enough notice: “I would like to discuss how my role and compensation align after the scope changes this year.” Send the one-page case in advance if the manager prefers preparation. Do not circulate confidential company information or salary screenshots from colleagues.',
'Choose a calm period when possible, but do not wait indefinitely for a perfect quarter. Business pressure can delay budgets for months. If immediate action is impossible, seek a written decision date and measurable interim criteria rather than accepting “later” without ownership.',
'Coordinate with performance reviews but do not assume a high rating automatically sets pay. Performance, market, band position and budget can be separate inputs. Ask how they connect. A “meets expectations” employee may be under market, while an exceptional employee near a band ceiling may face structural limits.',
'Prepare the manager for objections from above. Provide current role map, concise outcomes, source-backed range and requested mechanism. A manager who supports the case should be able to explain it in two minutes. Offer supporting evidence without asking them to forward a personal financial story.',
'If a reorganization or acquisition is underway, ask how roles and bands will be mapped. A temporary freeze can be real, but it should not erase the case. Preserve agreed scope and revisit date so the new structure does not treat expanded duties as an undocumented starting point.',
'Do not issue an ultimatum unless genuinely ready to leave and the consequence is professionally appropriate. Threatening with a nonexistent offer damages trust. A credible negotiation can be firm: state the gap, request, timeline and decision you will make after receiving the answer.',
'Account for payroll effective dates. Approval in November may apply immediately, next cycle or next fiscal year. Confirm retroactivity, bonus calculation, benefit impacts and the first paycheck affected. A verbal percentage without an effective date is incomplete.',
'Calendar knowledge transforms waiting into process. Record submission date, approvers, next checkpoint and expected outcome. Follow up as agreed rather than every few days. If the organization refuses to describe any path, that is information for the employee’s external career decision.' )
sec('Make the Ask Specific and Easy to Repeat',
'Open with role and value, not apology: “My responsibilities now include X and Y, and the last two quarters produced A and B. Based on the role’s current scope and the market range, I am requesting a base salary of $84,000.” Then stop. Silence gives the manager room to respond.',
'Use a target supported by the range rather than a huge number chosen only to bargain down. An aggressive but defensible anchor can help, while a fantasy anchor lets the employer dismiss the analysis. Know the desired result, acceptable alternative and point at which external search becomes rational.',
'Practice aloud until the script sounds like ordinary speech. Rehearse questions about attribution, data, timing, band, performance and future scope. Do not memorize a dramatic monologue. The meeting should be a decision conversation, not a courtroom closing statement.',
'Expect the manager to need time. Ask what process follows, who decides, what information is missing and when an answer will arrive. “I will look into it” becomes useful only with a date and next action. Send a brief factual recap afterward.',
'If the manager says the budget is fixed, test the constraint respectfully. Is there an off-cycle market process, promotion path, one-time bonus, review-date acceleration or next-budget submission? Do not immediately offer to do more work for the same vague promise.',
'If performance concerns appear for the first time, ask for concrete examples, expected standard, evidence and review date. A compensation meeting should not become an indefinite remediation fog. Document goals and request regular feedback so the criteria cannot shift silently.',
'Avoid arguments based on coworker gossip. Internal comparisons can reveal a concern, but incomplete information about scope, tenure, location or compensation can mislead. Ask for band position and equity review through appropriate channels. Where discrimination may be involved, preserve facts and use formal advice rather than confrontation alone.',
'Name future value without promising impossible outcomes. Explain the next responsibilities, project or capability the adjustment supports. The case remains grounded in value already demonstrated; future priorities show continuity rather than turning the raise into advance payment for an undefined workload.',
'Keep emotion regulated without pretending the issue is unimportant. It is reasonable to pause, take notes or request time before accepting an alternative. Do not resign in the room unless that decision was made independently and the practical consequences are understood.',
'Close by confirming the answer, owner and date. If approved, request written terms. If pending, record the process. If declined, move directly to criteria and alternatives. Every ending should produce a next step instead of leaving both parties with different memories.' )
sec('Negotiate the Package When Base Pay Is Constrained',
'Base salary deserves priority because it recurs, but total compensation can solve real needs. The Department of Labor’s 2026 salary-negotiation guide advises evaluating salary, benefits, hours, flexibility, vacation and retirement plans as a package. [[S3|Its framework]] supports comparing terms rather than accepting a headline alone.',
'Build an alternative menu before the meeting: sign-on or retention bonus, guaranteed review date, title and level, additional leave, schedule flexibility, remote arrangement, retirement contribution, education funding, professional dues, equipment or a defined promotion plan. Choose items the household values, not decorative perks.',
'Value each item after restrictions. A $5,000 bonus is one-time and generally taxable compensation. Extra leave matters only if workload permits use. Education funding may require repayment after departure. Remote work can save commuting time but may affect location pay. Convert promises into usable value.',
'BLS Employer Costs for Employee Compensation data show why package review matters: in March 2026, private-industry employer costs averaged $32.60 per hour for wages and $14.01 for benefits. [[S2|The aggregate data]] do not price one job, but they demonstrate that benefits are a material part of compensation.',
'Do not trade durable base salary for a perk the employer can revoke easily unless the value and risk are acceptable. Ask whether flexibility or remote terms will appear in the offer or employment record, who can change them and whether location-based pay applies.',
'A shorter written review period can be valuable only with criteria, decision maker and target. “We can revisit in six months” is not compensation. Convert it into a calendar date, required outcomes, intended level and the process for an adjustment if criteria are met.',
'Title without scope or pay can help external signaling but can also create uncompensated responsibility. Confirm reporting line, level, duties and salary band. If the employer offers title alone, decide whether it advances a defined career step or merely relabels existing underpayment.',
'IRS Publication 15-B explains that fringe benefits are generally taxable unless a specific exclusion applies. [[S7|That guidance]] means a perk’s face value may not equal spendable value. Ask payroll or a tax adviser about treatment rather than assuming “benefit” means tax free.',
'Compare offers on an annualized worksheet: guaranteed cash, expected variable cash, employer retirement value, insurance cost difference, paid time, commute, schedule, vesting and risk. Keep uncertain bonus at a probability-adjusted or separate value so best-case compensation does not masquerade as guaranteed.',
'When a package agreement is reached, obtain written terms before withdrawing other options or making household commitments. Verify amount, effective date, title, reporting relationship, bonus formula, location, schedule and review date. Friendly intent is not a substitute for an accurate compensation record.' )
sec('Treat No as Information, Not the End of the File',
'A refusal can mean no budget, weak evidence, wrong timing, band ceiling, performance disagreement or unwillingness to pay market value. Ask which applies. The response determines whether to strengthen the internal case, pursue promotion, wait for a dated cycle or begin a serious external search.',
'Request measurable criteria: which responsibilities, outcomes or level signals are missing; who will evaluate them; what resources are available; and when the decision will be revisited. Avoid accepting “keep doing great work.” A useful development plan has observable completion and compensation linkage.',
'Send a short recap: current request, manager feedback, agreed criteria, support needed and review date. Invite corrections. This is not a hostile record; it prevents drift and gives both sides a shared operating plan.',
'Decide how long the wait is worth. Estimate the annual and monthly gap between current compensation and the defensible target, probability of internal correction, value of benefits and cost of changing jobs. Loyalty is a preference, not a calculation that automatically closes the gap.',
'Test the external market ethically. Update the résumé, portfolio and references; speak with recruiters; and apply selectively. An actual offer provides information and choice, but do not solicit one merely as a bluff. Be prepared to accept or decline on the full package.',
'Counteroffers deserve caution. A higher salary can solve pay, but it may not repair stalled progression, poor management or changed trust. Compare the counteroffer with the external role, reasons for leaving, vesting, risk and written terms. There is no universal rule to accept or reject.',
'Compensation discrimination is different from an ordinary negotiation gap. The EEOC states that federal laws protect compensation without discrimination based on covered characteristics and that compensation includes salary, bonuses, stock, leave and benefits. [[S6|Its guidance]] also describes protection against retaliation for opposing unlawful discrimination.',
'Preserve contemporaneous facts if inequity is suspected: role, work, dates, statements, pay decisions, policies and comparators lawfully known. Do not take confidential records without authorization. Use internal reporting, union support, legal counsel or the appropriate agency based on circumstances and deadlines.',
'A no can still improve future leverage when the employee gains a title, documented scope, development resource or written review. Accept those only if they are genuinely useful and do not waive the central question. Continue tracking outcomes until the agreed date.',
'If the organization repeatedly expands duties while avoiding pay, the decision may no longer be how to ask better. It may be whether to sell the same skills in a labor market that prices them differently. A negotiation process should clarify that decision before years of compounding are lost.' )
sec('Give Every New Dollar a Job Before It Arrives',
'A raise can disappear into larger recurring costs because the household experiences only the net paycheck. Estimate federal, state, payroll and benefit effects; then wait for the first representative pay stub before automating the exact amount. The gross percentage is not the spendable percentage.',
'Use a split that reflects current priorities rather than a universal ratio. Direct portions to retirement, emergency savings, high-rate debt, near-term goals and lifestyle. Including some present enjoyment can make the plan durable, while assigning all of it before spending prevents silent expansion.',
'Increase savings through payroll or an automatic transfer timed after payday. If the raise starts midmonth or includes retroactive pay, separate the one-time amount from the ongoing increment. Do not build a permanent bill around temporary back pay or a bonus.',
'Revisit insurance and retirement elections if compensation changes employer match, contribution capacity or coverage needs. A promotion can add travel, commuting, childcare or professional expense. The real household gain equals added net pay minus new costs required to perform the role.',
'Update withholding after a substantial change, especially in a two-income household or when bonus and equity compensation are involved. A larger refund is not the objective; sufficient payment and predictable cash flow are. Inspect payroll implementation rather than assuming HR approval reached payroll correctly.',
'Keep career capital funded. Reserve some increase for credentials, conferences, portfolio work or tools only when they serve a clear path. The employer should pay legitimate business expenses where appropriate; personal investment should remain portable if the next raise requires a different organization.',
'Schedule a 30-day check: written terms correct, title updated, payroll rate accurate, bonus and benefit effects understood, automations working. Schedule a 90-day check on expanded responsibilities and support. The late photograph of a person planning at a laptop fits this operating phase, after the meeting becomes a calendar.',
'Retain the evidence file after approval. It becomes the baseline for the next review, promotion or job search. Add future outcomes without relitigating the old decision. Compensation management is a recurring career system, not a single courageous conversation.',
'Measure the long-term effect. A $6,000 annual increase invested partly over several years can matter far more than one severe month of cost cutting, but only if tenure, performance and saving behavior sustain it. Do not use potential investment growth as a promise; use it as a reason to act on recurring income early.',
'The durable strategy has two tracks: operate spending responsibly and keep labor income accurately priced. Budgeting protects the downside; negotiation expands capacity. Build the role map, market range, evidence, process and follow-up calendar so the raise request is a decision-ready case rather than a plea.' )
S[-1]['paragraphs'].append('Write the next compensation checkpoint into the household calendar before closing the file. A recurring review protects earning power from becoming an occasional reaction to frustration and keeps career evidence current between formal cycles.')
S=[S[i] for i in (0,1,2,4,3,5,6,7,8)]
summary=[
'A raise request succeeds or fails as an organizational decision, not as a response to personal bills. Financial pressure can motivate action, but the employer needs a case tied to current scope, demonstrated outcomes, market position and its compensation process. Begin months before a review window rather than waiting for an urgent need.',
'Map the job actually performed. Compare original duties with current responsibilities, decisions, stakeholders, risk and people supported. Separate temporary coverage from sustained higher-level work. Translate invisible contributions such as mentoring, documentation and prevention into observable effects without inventing unsupported savings.',
'Use market data as a range. Match occupation, level, geography, industry and schedule. BLS wage distributions show 10th through 90th percentiles and explain that experience, education, location and industry influence position. A median is not an entitlement, and a high percentile requires evidence that the role aligns with it.',
'Build outcome evidence the organization already trusts: revenue enabled, cost reduced, time released, defects prevented, customers retained, capacity expanded or risk lowered. State baseline, period, quantity and source. Claim only the employee’s contribution to team results and label estimates honestly.',
'Learn the employer’s calendar and mechanism. Merit, promotion, market, equity, retention and bonus decisions can use different budgets and criteria. Ask when recommendations are submitted, who approves them, whether an off-cycle process exists and when payroll changes become effective.',
'Make a specific request. Name the target base salary or defensible range, effective date and title or level if relevant. Open with changed scope and two or three outcomes, cite the market range and ask directly. Then let the manager respond. A rehearsed conversation should still sound natural.',
'If immediate approval is impossible, request the actual process: missing evidence, decision maker, criteria, budget window and answer date. Convert “revisit later” into a written review date with measurable outcomes. Follow up with a concise factual recap rather than repeated informal reminders.',
'Negotiate the package when base salary is constrained, but value alternatives realistically. A bonus is temporary, leave matters only when usable, education may have repayment conditions and flexibility may be revocable. Title alone can create uncompensated scope. Compare guaranteed cash, variable pay, retirement, insurance, leave, schedule and restrictions.',
'Treat a refusal as information. Determine whether the problem is budget, timing, evidence, performance, band ceiling or unwillingness to pay market value. Set a rational wait period and test external options honestly. Never bluff with a nonexistent offer or threaten departure unless prepared to follow through.',
'Pay discrimination requires a different response from ordinary bargaining. Preserve lawful contemporaneous facts, use formal internal or external advice and respect filing deadlines. Compensation protections can cover salary, bonuses, stock, leave and benefits, and retaliation for opposing unlawful discrimination is prohibited.',
'When a raise arrives, estimate the net paycheck and assign it before lifestyle expands. Separate retroactive or bonus money from the recurring increase. Automate saving or debt payments after checking the first correct pay stub, update withholding where appropriate and account for new work-related costs.',
'Run 30-day and 90-day reviews. Verify written terms, payroll, title, benefit effects, expanded responsibilities and support. Keep the evidence file as the baseline for the next promotion or job search. Responsible spending protects the household, while accurate labor pricing expands its long-term capacity.',
'A one-page negotiation file should remain usable after the meeting. Record the role change, verified outcomes, market sources, requested adjustment, employer response, decision owner and next date. Update it quarterly. This creates continuity when managers change and prevents the next compensation conversation from depending on memory, urgency or a single recent project. Review the file before budgets close, not merely when annual meetings appear on the calendar, so evidence can influence the actual allocation decision.' ]
faq=[
{'question':'Should personal expenses be part of a raise request?','answer':'They can explain personal motivation, but the employer-facing case should rely on role scope, results, market evidence and compensation process.'},
{'question':'Is the market median the correct salary for everyone?','answer':'No. Occupation match, experience, level, geography, industry, schedule and internal band position affect a defensible range.'},
{'question':'How many accomplishments should be presented?','answer':'Lead with three to five verified outcomes closely tied to your contribution and retain detailed evidence as backup.'},
{'question':'What if the manager says there is no budget?','answer':'Ask about off-cycle adjustments, promotion, a bonus, alternative terms and a specific next budget date with measurable criteria.'},
{'question':'Should an external offer be used as leverage?','answer':'Only if genuine and you are prepared to accept or decline based on the full package. Never invent an offer.'},
{'question':'What should happen after a raise is approved?','answer':'Confirm written terms, inspect payroll, update automations and withholding, and review responsibilities after 30 and 90 days.'}]
glossary=[
{'term':'Base salary','definition':'Recurring guaranteed cash compensation before bonuses and most deductions.'},
{'term':'Compensation band','definition':'An employer’s pay range for a role, level or job family.'},
{'term':'Market adjustment','definition':'A pay change intended to align compensation with external labor-market rates.'},
{'term':'Merit increase','definition':'A pay increase connected to assessed performance under an employer program.'},
{'term':'Salary compression','definition':'A narrow pay difference between newer and more experienced employees or adjacent levels.'},
{'term':'Total compensation','definition':'Salary plus bonuses, benefits, retirement, leave, equity and other employment value.'},
{'term':'True-up review','definition':'A later reconciliation against agreed criteria, outcomes or compensation terms.'},
{'term':'Walk-away point','definition':'The outcome below which the employee chooses another option rather than accepting the deal.'}]
visuals=[
{'type':'table','title':'A raise case needs four kinds of evidence','caption':'A decision sheet is stronger when each claim has a source and a business consequence.','source':1,'after_section':'Map the Job You Actually Perform','data':[{'Evidence':'Role scope','Question answered':'What work and accountability changed?'},{'Evidence':'Outcomes','Question answered':'What improved because of the contribution?'},{'Evidence':'Market range','Question answered':'How is comparable work priced?'},{'Evidence':'Internal mechanism','Question answered':'Which process can approve the change?'}]},
{'type':'bar','title':'A market range is a distribution, not one magic number','caption':'Illustrative percentile index only; use the current BLS occupation, location and industry data for an actual request.','source':1,'after_section':'Use Market Data as a Range, Not a Verdict','labels':['10th percentile','25th percentile','Median','75th percentile','90th percentile'],'values':[55,72,100,128,155]},
{'type':'bar','title':'Benefits are a material part of employer compensation cost','caption':'Average private-industry employer cost per hour in March 2026; these aggregates do not value one individual offer.','source':2,'after_section':'Negotiate the Package When Base Pay Is Constrained','labels':['Wages and salaries','Benefits'],'values':[32.6,14.01]},
{'type':'table','title':'Every answer needs a next action','caption':'Illustrative negotiation response map.','source':3,'after_section':'Treat No as Information, Not the End of the File','data':[{'Employer answer':'Approved','Next action':'Confirm amount, effective date and payroll'},{'Employer answer':'Budget closed','Next action':'Identify next submission date and interim option'},{'Employer answer':'Evidence incomplete','Next action':'Agree measurable criteria and review date'},{'Employer answer':'Band ceiling','Next action':'Evaluate promotion, package or external market'}]}]
slug='build-the-case-before-asking-for-a-raise'
photos=[
{'url':f'https://raw.githubusercontent.com/kushalkumardagaca-png/blogger-bot/main/assets/master/{slug}/photo-1.jpg','alt':'Professionals discussing documents during a compensation meeting','caption':'Photo: Vlada Karpovich / Pexels License','width':1600,'height':900,'source_page':'https://www.pexels.com/photo/business-partners-having-a-meeting-at-the-office-7433848/','license':'Pexels License','license_url':'https://www.pexels.com/license/','creator':'Vlada Karpovich'},
{'url':f'https://raw.githubusercontent.com/kushalkumardagaca-png/blogger-bot/main/assets/master/{slug}/photo-2.jpg','alt':'Professionals analyzing performance charts on a laptop and tablet','caption':'Photo: Mikhail Nilov / Pexels License','width':1600,'height':900,'source_page':'https://www.pexels.com/photo/people-looking-at-graphs-on-a-laptop-and-a-digital-tablet-6930432/','license':'Pexels License','license_url':'https://www.pexels.com/license/','creator':'Mikhail Nilov'},
{'url':f'https://raw.githubusercontent.com/kushalkumardagaca-png/blogger-bot/main/assets/master/{slug}/photo-3.jpg','alt':'Professional writing a follow-up plan beside a laptop','caption':'Photo: Kaboompics.com / Pexels License','width':1600,'height':900,'source_page':'https://www.pexels.com/photo/person-writing-on-notebook-while-using-a-laptop-5387268/','license':'Pexels License','license_url':'https://www.pexels.com/license/','creator':'Kaboompics.com'}]
sources=[
{'name':'U.S. Bureau of Labor Statistics','title':'Using Occupational Employment and Wage Statistics Data During Salary Negotiations','url':'https://www.bls.gov/oes/earnings.htm','date':'2026','use':'Occupation, percentile, location and industry wage evidence.'},
{'name':'U.S. Bureau of Labor Statistics','title':'Employer Costs for Employee Compensation — March 2026','url':'https://www.bls.gov/news.release/archives/ecec_06122026.pdf','date':'2026','use':'Wage, salary and benefit components of total compensation.'},
{'name':'U.S. Department of Labor Veterans’ Employment and Training Service','title':'Salary Negotiation Participant Guide','url':'https://www.dol.gov/sites/dolgov/files/VETS/files/SalaryNegotiation_PG_Interactive_Feb2026.pdf','date':'2026','use':'Research, package evaluation and negotiation process.'},
{'name':'O*NET','title':'O*NET OnLine','url':'https://www.onetonline.org/','date':'2026','use':'Occupation tasks, skills and responsibility definitions.'},
{'name':'U.S. Bureau of Labor Statistics','title':'Employment Cost Index — March 2026','url':'https://www.bls.gov/news.release/archives/eci_04302026.pdf','date':'2026','use':'Broad changes in wages, benefits and compensation costs.'},
{'name':'U.S. Equal Employment Opportunity Commission','title':'Facts About Equal Pay and Compensation Discrimination','url':'https://www.eeoc.gov/laws/guidance/facts-about-equal-pay-and-compensation-discrimination','date':'2026','use':'Covered compensation, discrimination and retaliation protections.'},
{'name':'Internal Revenue Service','title':'Publication 15-B, Employer’s Tax Guide to Fringe Benefits','url':'https://www.irs.gov/publications/p15b','date':'2026','use':'Tax treatment and valuation of employee fringe benefits.'},
{'name':'U.S. Department of Labor Wage and Hour Division','title':'Fact Sheet 17U: Nondiscretionary Bonuses and Incentive Payments','url':'https://www.dol.gov/agencies/whd/fact-sheets/17u-overtime-bonuses','date':'2026','use':'Distinguishing salary, nondiscretionary bonus and overtime concepts.'}]
old=json.loads((ROOT/'master_packages/rewrites/post_824646953557055227.json').read_text())
p={'title':'Build the Case Before Asking for a Raise','meta_description':'Turn a raise request into a decision-ready case using role scope, measurable outcomes, credible market ranges, timing and package alternatives.','entities':['salary negotiation','pay raise','total compensation','market salary range','career planning'],'geography':['United States'],'temporal_coverage':'2026','module_headings':{'contents':'Build the compensation case','summary':'The raise strategy in brief','faq':'Before the compensation meeting','glossary':'Negotiation terms','sources':'Evidence behind the case','internal_links':'Keep strengthening your earning power','external_sources':'Official pay and labor guidance'},'sections':S,'summary':summary,'faq':faq,'glossary':glossary,'visuals':visuals,'photos':photos,'sources':sources,'internal_links':[{'title':'Daily Yield Calculators','url':'https://dailyyield.blogspot.com/p/calculator_0908148622.html','relevance':'Model the after-tax and long-term effect of compensation changes.'},{'title':'Daily Yield Articles','url':'https://dailyyield.blogspot.com/p/daily-articles.html','relevance':'Continue with evidence-led career and salary systems.'}],'low_view_posts':old['low_view_posts']}
out=ROOT/'arena_work/post_6406126111566056260.json';out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n');print(validate(p))
