import json,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1];sys.path.insert(0,str(R));S=[]
def sec(h,*p):S.append({'heading':h,'paragraphs':list(p)})
sec('The Model Finds Candidates, Not Savings',
"An AI spending audit can scan thousands of transaction descriptions faster than a person, group similar merchants and flag patterns that deserve attention. It cannot know whether a payment was authorized, valuable, reimbursable, shared with someone else or already cancelled. Its output is a review queue, not a verdict and certainly not money saved.",
"That distinction prevents the most common exaggeration. If a model highlights £1,200 of annual charges, it has found £1,200 of candidates under its assumptions. Real savings exist only after the owner verifies each charge, takes a valid action, avoids replacement spending and confirms that later statements no longer contain the cost. Discovery, decision and realization are separate stages.",
"Useful AI here is less like an autonomous financial adviser and more like a tireless junior analyst. It can normalize merchant strings, detect repeated amounts, compare months and draft questions. A human remains accountable for context, cancellation, disputes and data permissions. No model should receive authority to move money merely because it can describe the ledger.",
"A responsible audit begins with a written objective: identify recurring charges, duplicate services, fee patterns, price increases and habitual spending that no longer matches priorities. It does not begin with a vague instruction to 'fix my finances.' Narrow tasks produce outputs that can be checked against source transactions and reduce the temptation to accept confident speculation.",
"The National Institute of Standards and Technology describes generative-model confabulation as confidently presented erroneous content and identifies data privacy as a distinct risk. [[S3|Its generative-AI profile]] supports two operating rules: verify every finding against the ledger and disclose the least sensitive data needed for the task. Fluency is not evidence of correctness.",
"An audit should preserve transaction facts while removing unnecessary identity. The model may need posting date, a stable merchant alias, amount, account type and perhaps a user-supplied category. It usually does not need an account number, card number, home address, employer, bank login, full name or unredacted statement PDF. Data minimization starts before upload.",
"This guide uses sterling examples because the legacy claim was expressed in pounds, but its process is jurisdiction-neutral until a legal right or dispute route is discussed. Readers should follow their bank agreement and local law. The cited U.S. agencies provide strong operational guidance on data sharing, dark patterns and AI risk; they do not govern every reader everywhere.",
"The deliverable is an evidence table: transaction family, dates, total paid, reason flagged, confidence, human decision, action date and confirmed savings. A persuasive paragraph from a chatbot is not enough. Every claim should trace to rows the owner can inspect and every projected saving should remain labelled projected until statements prove it." )
sec('Draw the Data Boundary Before Connecting Anything',
"Choose the least invasive route that can answer the question. A local spreadsheet or offline script can often identify repeated descriptions without connecting a third-party app. A bank's built-in analytics may avoid another data recipient. An authorized data-sharing connection can improve automation, but convenience should be weighed against access scope, retention and the service's business model.",
"The Consumer Financial Protection Bureau explains that budgeting services may access bank and card data once or continuously. [[S1|Its data-sharing checklist]] tells consumers to examine which data is shared, how often accounts are accessed, whether information goes to other parties, how long it is stored, whether the service can move money, and how to stop access and delete data.",
"Ask those questions before account linking, not after the audit. Read the privacy notice and terms for collection, advertising, model training, human review, service providers, retention, deletion and breach handling. If the provider cannot clearly state whether prompts or uploads train a model, assume the answer is unresolved and use a less sensitive workflow.",
"Prefer tokenized authorization or an institution-supported interface over giving a budgeting tool the bank password. The CFPB's consumer-protection principles say access should not require consumers to share account credentials and that third parties should access only data necessary for the selected product. [[S2|Those principles]] also emphasize informed consent, accuracy, security and practical dispute resolution.",
"Do not paste raw statements into a general chatbot merely because the chat window feels private. Statement PDFs can contain names, addresses, partial account numbers, balances, transaction locations and metadata. Redact first, export only needed columns, replace merchant names when the exact identity is unnecessary, and delete intermediate files from cloud drives and download folders after the validated work is retained.",
"Separate read access from payment authority. A spending classifier needs transaction history; it does not need permission to initiate transfers, open products or cancel services automatically. If a tool bundles analysis with broader authority, decline the extra scope or choose another method. The principle is simple: observation should not silently become execution.",
"Record a permission ledger with provider, accounts connected, data categories, purpose, authorization date, next review date and revocation path. This turns forgotten app access into a manageable inventory. Calendar a check after the audit to revoke access that no longer serves a purpose and confirm deletion under the provider's actual process.",
"Regulatory protections change and may be challenged, delayed or reconsidered. The CFPB's 2025 advance notice states that its personal-financial-data-rights rule was being comprehensively reexamined and its compliance dates had been stayed and were expected to change. [[S8|That record]] is a reason to verify current rights rather than treating a product's compliance claim as permanent protection." )
sec('Build a Ledger the Model Can Actually Read',
"Export at least twelve complete months when the goal includes annual renewals; use eighteen months when seasonality, insurance or infrequent memberships matter. Include every spending account that can carry recurring charges: current accounts, credit cards, payment apps and store cards. Excluding one account can make a transferred subscription look cancelled or make a duplicate impossible to see.",
"Keep one immutable source file and work from a copy. Standardize columns for account alias, posting date, transaction date when available, raw description, amount, currency, debit or credit, and user notes. Preserve the raw description even after creating a cleaned merchant field because the original text is the evidence used to verify the model's grouping.",
"Normalize cautiously. Remove changing reference numbers and terminal codes only when they are clearly incidental. Map spelling variants to one merchant family, but do not merge unrelated companies because a model says their names look similar. Payment processors can represent many underlying sellers, and a single brand can charge through different entities.",
"Exclude transfers, card payments and refunds from spending totals only after matching them. A transfer between owned accounts is not consumption, while a transfer to another person may be. A credit-card payment and the card's individual transactions must not both be counted. Refunds should link to the original purchase rather than becoming negative income.",
"Currency needs explicit handling. Preserve the charged currency and amount, the account's converted amount, and any foreign-transaction fee. Do not let a model add pounds, dollars and euros as if they were identical. For a household-level report, state the conversion method and date or keep currencies separate until the owner decides.",
"Create deterministic features before invoking AI: month, day interval from prior charge, absolute amount, amount-change percentage, merchant frequency and account count. Simple code can find exact repeats and near-regular intervals. The model is most useful for ambiguous description cleanup and explanation, while arithmetic should remain in formulas that can be reproduced.",
"Remove transaction narratives that reveal health, religion, political activity or precise locations when those details are unnecessary. Replace them with stable aliases and maintain the mapping locally. A model can identify that MERCHANT_017 charges £14.99 monthly without knowing what sensitive service sits behind that alias.",
"Hash or label rows so findings can cite exact records without copying the entire ledger into prose. For example, a flagged family can reference rows T0041, T0078 and T0115. The reviewer can jump from recommendation to source, and a corrected merchant mapping can be rerun without losing the original audit trail." )
sec('Use Several Signals to Find Recurring Charges',
"A repeated amount is only one signal. Rent may repeat but is not waste; usage-based subscriptions may vary; annual memberships appear once; trial conversions change price; and a merchant may split charges. Build a score from interval regularity, merchant similarity, amount stability, subscription language, cross-account duplication and prior user labels, then expose the reasons behind the score.",
"Start with cadence windows rather than exact dates. Monthly charges can post every 28 to 33 days because of weekends and month length. Quarterly, semiannual and annual windows need wider tolerances. A charge on the first business day is still regular even when the calendar date moves. The audit should show observed gaps rather than simply declaring 'monthly.'",
"Price creep is a separate pattern. Compare the latest charge with the earliest comparable charge and mark step changes, not ordinary foreign-exchange noise or tax adjustments. A service rising from £9.99 to £13.99 costs £48 more over the next year if the new monthly price continues, but that is projected exposure, not already-realized savings.",
"Search for free-trial conversions by pairing a small or zero introductory event with later recurring debits, while recognizing that zero-value authorizations may not appear in exports. Search email locally for receipts only if the owner chooses; do not hand an AI unrestricted mailbox access just to improve merchant matching.",
"Duplicate-service detection requires function, not just merchant identity. Two music services may be deliberate for different household members, while two cloud-storage plans under one ecosystem may overlap. Ask what job each service performs, who uses it, what data depends on it and whether one plan already includes the other.",
"Fees form their own family: overdraft, out-of-network cash withdrawal, account maintenance, late payment, foreign transaction, delivery and platform service charges. The model can total them and identify clusters, but it should not label a fee unlawful or refundable. The owner must check the account terms and the facts around each charge.",
"Habitual discretionary purchases are not subscriptions and should not be disguised as accidental waste. A weekly lunch or ride-hail pattern may be fully intentional. Present frequency, total and alternatives without moral language. An audit is better when it helps the owner compare spending with priorities, not when it calls every pleasure a leak.",
"Require the model to return structured output with merchant family, row IDs, cadence, amount range, annualized estimate, flag reason, uncertainty and verification question. Reject findings with no cited rows. If the tool cannot explain why it grouped transactions, lower confidence and review the raw descriptions manually." )
sec('Make the Machine Show Its Work',
"Prompt design should force restraint. Tell the model not to invent missing transactions, not to infer personal circumstances, not to recommend disputes, and not to classify a charge as unwanted. Ask it to separate observed facts from calculations and suggestions. Provide allowed categories and an 'uncertain' option so every row is not forced into a false answer.",
"Run the same ledger through two passes. The first pass groups merchant aliases and identifies cadence. After the owner corrects mappings, the second pass scores candidates and drafts verification questions. Mixing cleanup, judgement and recommendations in one prompt makes errors harder to locate and encourages the model to defend an early assumption.",
"Test a sample before the full dataset. Seed known cases: one monthly subscription, one irregular utility, one refund, one transfer, one duplicate card payment and one annual renewal. Measure whether the system catches the recurring item without double-counting or mislabelling essentials. If the test fails, revise rules before exposing more data.",
"Recalculate totals outside the model. For each merchant family, sum source rows with spreadsheet formulas or deterministic code; count distinct charges; calculate intervals; and annualize only with an explicit formula. A language model can produce polished arithmetic errors. The ledger, not generated prose, must determine the number.",
"Use confidence bands tied to evidence. High confidence might require at least three charges, regular intervals and stable merchant identity. Medium confidence may have only two charges or variable amounts. Low confidence includes one annual-looking payment or processor ambiguity. Confidence reflects pattern evidence, not whether the charge should be cancelled.",
"Inspect omissions as well as flags. Compare model-assigned rows with the source row count and total debits. Every row should be assigned, excluded with a reason or held uncertain. A result that explains ninety percent of spending while silently dropping ten percent is not complete, even if its visible recommendations sound intelligent.",
"Keep the model's output versioned with prompt, tool, date, source-file hash and correction notes. Financial apps and model behavior change. Reproducibility allows the owner to explain why a candidate appeared, rerun after fixing a mapping and compare future audits without pretending two different systems are identical.",
"Never put authentication codes, security answers or full credentials into a prompt. Prompt injection can also arrive through imported text, such as a merchant memo that tells an assistant to ignore instructions. Treat transaction text as untrusted data and prohibit tools or actions during analysis. The audit environment should read rows, not obey them." )
sec('Human Verification Turns Flags into Decisions',
"Open the source statement or account activity for every candidate. Confirm merchant, amount, frequency and account owner. Then locate the service account, current plan, renewal date, cancellation terms and household user. The model cannot see that a £7.99 charge supports a child's schoolwork or that an unfamiliar descriptor belongs to a valued local business.",
"Classify each candidate as keep, reduce, switch, cancel, dispute through the proper route, or investigate. Add a reason and decision owner. 'Cancel' is not the default: downgrading may retain needed data, switching billing frequency may lower cost, and keeping a high-value service is a successful audit decision because uncertainty was removed.",
"Verify dependencies before cancellation. Cloud storage may hold the only copy of photographs; a phone plan may finance a handset; a software subscription may store files in a proprietary format; insurance or monitoring may protect against a larger risk. Export data, identify alternatives and understand loss of access before pressing the final button.",
"Do not use an AI label as evidence of fraud. An unfamiliar descriptor can be a legitimate processor, a family purchase or delayed posting. For genuinely unrecognized activity, contact the financial institution promptly through a trusted channel and follow its dispute procedure. In the United States, CFPB guidance explains that protections and timing vary by account and transaction type. [[S6|Its unauthorized-transaction resource]] is a starting point, not a substitute for the account agreement.",
"Watch for cancellation friction. The FTC's review of 642 subscription sites and apps found that nearly 76% used at least one possible dark pattern and nearly 67% used multiple possible dark patterns, without determining that each instance violated law. [[S5|The review]] supports preserving screenshots, confirmation numbers and effective dates rather than assuming one click completed cancellation.",
"Dark patterns include hidden terms, preselected choices, obstructed cancellation and confirm-shaming. The FTC staff report describes free trials that unexpectedly convert to recurring charges and interfaces that steer people away from cancellation. [[S4|Its examples]] help reviewers recognize friction, but the response should remain factual: read the screen, decline unrelated offers and retain proof.",
"For shared households, assign one person to contact the provider but require consent from the service's actual user. A technically duplicated subscription can serve separate profiles or privacy needs. Savings imposed without context often reappear as resentment or replacement spending, which is why a household audit should surface decisions rather than automate them.",
"Update the evidence table immediately after each decision. Record what changed, expected effective date, refund promised, final service date and where confirmation is stored. If the provider offers a retention discount, record its duration and future price so a temporary concession does not become the next hidden increase." )
sec('Cancel Safely and Close the Loop',
"Use the provider's official account page or a verified support channel, not a cancellation link supplied by an unknown message. Sign in independently, inspect the plan and follow the complete flow. A model can draft a concise request, but the owner should review it and never give the model access to send messages from a financial or primary email account.",
"Capture evidence before and after: plan name, price, renewal date, cancellation policy, confirmation page, email and case number. Note whether access ends immediately or at the billing-period close. If the service contains data, export it first and test that the archive opens before deleting the account.",
"A cancelled card is not a universal cancellation method. Merchants may update credentials through account-updater services, and an unpaid contractual obligation can remain. Cancel with the provider and resolve the agreement; use bank controls as a backstop for unauthorized charges, not as a shortcut around valid terms.",
"Mark projected annual savings conservatively. If a £20 monthly service is cancelled with ten billing dates remaining in the next twelve months, projected twelve-month savings are £200, not £240. Subtract cancellation fees, lost discounts and necessary replacement cost. Do not count a refund and avoided future charge twice.",
"Wait for statement evidence. A cancellation made today can still have a valid final charge under the billing cycle. Match each expected stop date to subsequent statements, and reopen the issue if another charge appears outside the confirmed terms. Realized savings accrue only as expected charges fail to occur or verified fees are refunded.",
"Move the saved amount deliberately. Redirect it to a named goal through an automated transfer scheduled after the old charge would have posted. Without redirection, lower spending may dissolve into unrelated purchases and become impossible to distinguish. The audit succeeds when cash flow changes, not when a dashboard displays a celebratory number.",
"Remove service data and revoke financial access separately. Cancelling a subscription may not delete the account; deleting an app from a phone may not revoke its token; disconnecting at the bank may not erase retained data. Complete each step under the provider's process and update the permission ledger.",
"Set a reminder before any discounted retention period ends. A £5 offer for three months followed by £18 is not a permanent £13 monthly saving. Track the full price path and decide again before the next renewal. Temporary discounts belong in the calendar, not in annual savings as though they last forever." )
sec('Report Proven Savings, Not a Headline Number',
"Separate four totals: flagged annualized spend, approved changes, projected net savings and realized savings. Flagged spend is the broad review pool. Approved changes have an action decision. Projected net savings account for timing and replacement costs. Realized savings are confirmed by later transactions. Combining them creates the illusion that analysis itself produced cash.",
"Suppose an audit flags £1,200: £480 of valued services kept, £180 of duplicates cancelled, £240 of downgraded services with a £60 replacement, £120 of fees addressed and £180 uncertain. Approved gross reductions are £540, but projected net savings are £480 after replacement cost. The uncertain and retained amounts are not savings.",
"Then timing matters. If those changes occur halfway through the year, the first twelve months after the audit may avoid a different amount than a simple annualized total. Build candidate-level schedules from effective dates. A monthly cancellation, annual renewal prevented and one-time refund each have different realization patterns.",
"Report intervention cost too. Include cancellation fees, necessary purchases, time where material and any loss of annual discount from switching. The aim is not to manufacture the largest number. It is to make a defensible choice that improves money and service value after all consequences.",
"Track false positives as a quality metric. Divide incorrectly flagged candidates by total candidates reviewed, and separately measure missed known recurring charges in the test set. A high savings headline with many false positives creates review fatigue and can lead to harmful cancellations. Precision matters because human attention is limited.",
"Do not compare spending to generic benchmarks without context. Household size, disability, location, work requirements and values change what is reasonable. The audit can compare the owner with their own prior periods and stated priorities. A model should not shame a category because it differs from an average training example.",
"Build a short report with methods, data period, excluded accounts, limitations, candidate table, decisions, projected schedule, realized ledger and access-revocation status. This is more useful than a chatbot transcript because it distinguishes facts, assumptions and actions. Retain the minimum necessary report and delete raw copies that no longer serve the audit.",
"The number worth sharing is confirmed net savings over a stated period, not the largest amount an algorithm once highlighted. Honest reporting can show that a £1,200 review pool led to £480 projected savings and, months later, £235 realized. Smaller verified numbers are more valuable than impressive fiction." )
sec('Turn the Audit into a Controlled Routine',
"Run a light review monthly and a deep review quarterly or before major renewals. The monthly pass checks new recurring merchants, unexpected fees and failed cancellations. The deep pass revisits data permissions, duplicate functions, price changes and annual services. Frequency should reduce surprise without making financial monitoring a daily source of anxiety.",
"Maintain a known-recurring register with merchant alias, service owner, value statement, amount range, billing cadence, renewal date, payment account and decision. The next audit can compare the ledger against this register. New or changed items receive attention while stable, approved services do not consume the same review effort every month.",
"Use alerts from the financial institution for transactions and low balances when helpful, but tune them to avoid fatigue. One meaningful alert that prompts action is better than dozens ignored. A model may summarize alerts after the fact, yet the institution's record remains authoritative for posting and account status.",
"Review connected apps during every deep audit. Remove obsolete connections, rotate credentials if they were ever shared directly, inspect login history where available and confirm multifactor authentication. The spending audit should leave the data perimeter smaller or better documented, not create a permanent trail of forgotten access.",
"Retest the workflow when the model, prompt, export format or account mix changes. A method that worked last quarter can break when a bank changes merchant descriptors or an AI service changes behavior. Keep a compact synthetic test ledger with no real personal data so quality checks do not require re-uploading sensitive history.",
"Preserve human escalation. If a charge may be fraud, a cancellation is disputed, an essential service is at risk or the legal position is unclear, stop automation and contact the responsible institution or qualified adviser. The model's value is triage and organization; uncertainty involving rights or significant harm belongs with a person.",
"End every cycle with three questions: what was confirmed, what action changed cash flow, and what data access remains? Those questions expose decorative analytics. A colourful category chart can be informative, but it does not equal savings, cancellation proof or safe data governance.",
"AI earns its place when it reduces sorting time while increasing traceability. Give it redacted rows, constrained tasks and no execution authority. Require citations to transaction IDs, reproduce the arithmetic, make decisions in context and verify later statements. The result is not an autonomous money manager. It is a disciplined audit with a fast assistant." )
extra=[
"Set a materiality threshold before analysis. Tiny charges can matter when repeated, but reviewing every penny may cost more attention than it returns. Keep a low-value watchlist and escalate items when frequency, price growth or uncertainty makes them meaningful.",
"Check whether the provider offers an export-only workflow. Uploading a redacted CSV once can create less continuing exposure than a permanent account connection, provided the upload is deleted afterward and the service does not retain it for unrelated use.",
"Document exclusions beside the dataset. Cash spending, accounts not provided and transactions outside the date window limit conclusions. The report should never claim a complete household audit when its ledger covers only one card or excludes shared accounts.",
"Seasonality can imitate cancellation or recurrence. A sports service, school payment or energy plan may pause and return. Compare the same period in the prior year before treating a gap as proof that a charge ended or an annual payment appeared unexpectedly.",
"Ask for counterevidence. For every high-confidence candidate, require the system to state what observation would weaken its conclusion, such as a matching refund, a different underlying seller or irregular intervals. This simple step makes review less vulnerable to confirmation bias.",
"Keep and cancel decisions both need dates. A service intentionally retained today should return to review before renewal, especially if its price or usage changes. 'Keep' means the current evidence supports value; it is not a lifetime exemption from audit.",
"If a provider refuses cancellation or contradicts its confirmation, preserve communications and escalate through its complaint route and the payment institution where appropriate. Do not ask a chatbot to threaten legal action or invent statutory rights for leverage.",
"Use a reconciliation line in every report: source debit total equals categorized debits plus excluded debits plus unresolved debits. When the equation fails, the analysis is incomplete. This control catches dropped rows more reliably than visual inspection of charts.",
"A routine also needs a stop condition. End the session when high-value candidates are resolved, permissions are documented and remaining items are deliberately deferred. Endless optimization can consume time, expose more data and turn normal spending into avoidable anxiety."
]
for s,e in zip(S,extra):s['paragraphs'].append(e)
summary=[
"An AI spending audit should generate candidates, not make financial decisions. It can group merchant descriptions, detect recurring intervals and highlight price changes, but it cannot know whether a charge is authorized, valuable, reimbursable or already cancelled. Savings exist only after a person verifies the charge, acts safely and confirms later statements.",
"Define a narrow objective before choosing a tool: recurring charges, duplicate functions, fees, price creep or habitual spending. Use the least invasive method that works. A spreadsheet or local script may be enough. If linking accounts, examine data scope, access frequency, third parties, retention, deletion, payment authority and revocation.",
"Minimize the dataset. Keep dates, amounts, stable merchant aliases and account labels while removing credentials, account numbers, addresses and unnecessary sensitive narratives. Prefer institution-supported tokenized access to password sharing. Maintain a permission ledger and revoke connections that no longer serve the audit.",
"Export at least twelve complete months for annual renewals and include every spending account. Preserve an immutable source file and normalize a working copy cautiously. Match transfers, card payments and refunds to prevent double counting. Keep currencies distinct and calculate totals with reproducible formulas rather than generated prose.",
"Find recurring charges using several signals: cadence, merchant similarity, amount stability, price steps, cross-account duplication and known subscription language. Require structured output with transaction IDs, intervals, amount range, flag reason, uncertainty and a verification question. Every finding must trace to source rows.",
"Test the system on known examples, use an uncertain category and recalculate outside the model. Inspect omitted rows as well as visible flags. Version the prompt, tool, source hash and corrections. Treat imported transaction text as untrusted data and prohibit the analysis tool from taking actions.",
"Human review classifies each candidate as keep, reduce, switch, cancel, properly dispute or investigate. Check service ownership, dependencies, renewal terms and household use. An unfamiliar descriptor is not proof of fraud. For possible unauthorized activity, use the financial institution's trusted channel and applicable dispute procedure.",
"Cancel through the provider's official route and save the plan, renewal date, confirmation and effective date. Export needed data first. Cancelling a card is not the same as ending a contract. Remove service data, revoke financial access and calendar the end of any temporary discount as separate steps.",
"Separate flagged annualized spend, approved reductions, projected net savings and realized savings. Deduct replacement costs, fees and timing effects. A £1,200 candidate pool may produce a much smaller defensible saving, and that is honest. Redirect avoided payments to a named goal and confirm each result on later statements.",
"Repeat a light check monthly and a deeper audit quarterly. Maintain a register of approved recurring services, review connected apps and retest whenever the model or data format changes. AI is useful when it shortens sorting while preserving human judgement, reproducible arithmetic, privacy and a complete evidence trail.",
"State what the audit did not cover. Missing cash spending, excluded shared accounts, omitted currencies and a short date window limit any conclusion. Reconcile source debits with categorized, excluded and unresolved totals so dropped rows cannot hide behind a polished chart or confident explanation.",
"Set a materiality threshold and stop condition. Review attention should go first to meaningful recurring cost, price growth and uncertain activity rather than every tiny purchase. End the cycle when material candidates are resolved, remaining items are deliberately deferred and all data permissions are documented.",
"A keep decision is legitimate when a service provides value, but date it and revisit before renewal. If cancellation fails, retain communications and use the provider's complaint route or appropriate financial institution process. Never let a model invent rights, threaten action or substitute confidence for verified terms."
]
P={'title':'Make AI Prove Every Spending Leak','meta_description':'Use AI to audit recurring charges without surrendering privacy, trusting false matches or counting projected cuts as confirmed savings.','entities':['AI spending audit','recurring charges','subscription audit','financial data sharing','realized savings'],'geography':['United Kingdom','United States'],'temporal_coverage':'2024/2026','module_headings':{'contents':'Build an auditable review','summary':'The safe AI audit in brief','faq':'Before uploading the ledger','glossary':'Terms behind the audit','sources':'Evidence and safeguards','internal_links':'Continue your cash-flow review','external_sources':'Primary guidance and records'},'sections':S,'summary':summary,
'faq':[{'question':'Should a bank statement be pasted into a general AI chatbot?','answer':'Not unredacted. Export only needed fields, remove credentials and unnecessary sensitive details, and review the provider’s retention, training and deletion terms first.'},{'question':'Does a flagged annual amount equal savings?','answer':'No. It is a candidate pool. Savings become projected after a verified action and realized only when later statements confirm the cost was avoided.'},{'question':'Can AI cancel subscriptions automatically?','answer':'It should not receive execution authority for this audit. A person should verify ownership, dependencies, terms and the official cancellation route.'},{'question':'How much transaction history is needed?','answer':'Use at least twelve complete months for annual renewals and longer when seasonality or infrequent charges matter.'},{'question':'What if AI labels a charge as fraud?','answer':'Treat the label only as a prompt to investigate. Verify the descriptor and contact the financial institution through a trusted channel for genuinely unrecognized activity.'},{'question':'When should account access be revoked?','answer':'Revoke it when the audit no longer needs the connection, then separately address retained data under the provider’s deletion process.'}],
'glossary':[{'term':'Candidate spend','definition':'Charges flagged for review before any human decision or action.'},{'term':'Projected savings','definition':'Estimated future cost avoided after an approved change, net of known replacement costs.'},{'term':'Realized savings','definition':'Avoided charges or refunds confirmed by later account evidence.'},{'term':'Merchant normalization','definition':'Mapping variable transaction descriptions to a stable merchant family.'},{'term':'Cadence window','definition':'A date range used to detect approximate monthly, quarterly or annual repetition.'},{'term':'Tokenized access','definition':'Permission-based data access that avoids giving a third party the account password.'},{'term':'Data minimization','definition':'Sharing only information necessary for a defined task.'},{'term':'Confabulation','definition':'Confidently presented model output that is erroneous or false.'},{'term':'Dark pattern','definition':'Interface design that steers or obstructs consumer choice.'},{'term':'Permission ledger','definition':'A record of connected services, access scope, purpose and revocation status.'}],
'visuals':[{'type':'bar','title':'A large review pool can produce a smaller defensible saving','caption':'Illustrative pounds: retained, gross reductions, replacement cost and projected net savings from a £1,200 candidate pool.','source':3,'after_section':'Human Verification Turns Flags into Decisions','labels':['Candidate pool','Kept or uncertain','Gross reductions','Replacement cost','Projected net'],'values':[1200,660,540,60,480]},{'type':'bar','title':'Recurring detection needs more than equal amounts','caption':'Illustrative evidence score weights for triage; these are transparent audit assumptions, not a universal model.','source':3,'after_section':'Use Several Signals to Find Recurring Charges','labels':['Cadence regularity','Merchant match','Amount stability','Cross-account duplicate','User label'],'values':[35,25,15,15,10]},{'type':'bar','title':'Savings pass through four evidence stages','caption':'Illustrative pounds showing why flagged spend should not be reported as cash saved.','source':4,'after_section':'Report Proven Savings, Not a Headline Number','labels':['Flagged','Approved gross','Projected net','Realized to date'],'values':[1200,540,480,235]},{'type':'table','title':'The audit evidence ladder','caption':'Each stage requires a different record before the number can advance.','source':1,'after_section':'Make the Machine Show Its Work','data':[{'Stage':'Flagged','Required evidence':'Transaction rows and pattern reason'},{'Stage':'Verified','Required evidence':'Owner, service and terms confirmed'},{'Stage':'Actioned','Required evidence':'Cancellation or change confirmation'},{'Stage':'Realized','Required evidence':'Later statement or refund'}]}],
'photos':[{'url':'https://raw.githubusercontent.com/kushalkumardagaca-png/blogger-bot/main/assets/master/make-ai-prove-every-spending-leak/photo-1.jpg','alt':'Woman comparing paper receipts beside a laptop and notebook','caption':'Photo: Kaboompics.com / Pexels License','width':1600,'height':900,'source_page':'https://www.pexels.com/photo/woman-sitting-behind-the-desk-and-looking-at-receipts-5900074/','license':'Pexels License','license_url':'https://www.pexels.com/license/','creator':'Kaboompics.com'},{'url':'https://raw.githubusercontent.com/kushalkumardagaca-png/blogger-bot/main/assets/master/make-ai-prove-every-spending-leak/photo-2.jpg','alt':'Person checking transaction details on a smartphone while holding a payment card','caption':'Photo: Mikhail Nilov / Pexels License','width':1600,'height':900,'source_page':'https://www.pexels.com/photo/a-person-cashless-transaction-online-using-a-cellphone-6969809/','license':'Pexels License','license_url':'https://www.pexels.com/license/','creator':'Mikhail Nilov'},{'url':'https://raw.githubusercontent.com/kushalkumardagaca-png/blogger-bot/main/assets/master/make-ai-prove-every-spending-leak/photo-3.jpg','alt':'Person manually reviewing printed financial reports beside a laptop','caption':'Photo: Tima Miroshnichenko / Pexels License','width':1600,'height':900,'source_page':'https://www.pexels.com/photo/a-person-holding-a-pen-flipping-pages-of-a-report-6694878/','license':'Pexels License','license_url':'https://www.pexels.com/license/','creator':'Tima Miroshnichenko'}],
'sources':[{'name':'Consumer Financial Protection Bureau','title':'What to Consider When Sharing Your Financial Data','url':'https://www.consumerfinance.gov/archive/blog/what-to-consider-when-sharing-your-financial-data/','date':'2020','use':'Consumer checklist for access, use, retention and revocation.'},{'name':'Consumer Financial Protection Bureau','title':'Consumer Protection Principles: Consumer-Authorized Financial Data Sharing and Aggregation','url':'https://files.consumerfinance.gov/f/documents/cfpb_consumer-protection-principles_data-aggregation.pdf','date':'2017','use':'Access, data scope, consent, security and accuracy principles.'},{'name':'National Institute of Standards and Technology','title':'Artificial Intelligence Risk Management Framework: Generative AI Profile','url':'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf','date':'2024','use':'Confabulation, privacy and human oversight risks.'},{'name':'Federal Trade Commission','title':'Bringing Dark Patterns to Light','url':'https://www.ftc.gov/system/files/ftc_gov/pdf/P214800%20Dark%20Patterns%20Report%209.14.2022%20-%20FINAL.pdf','date':'2022','use':'Subscription and cancellation interface risks.'},{'name':'Federal Trade Commission','title':'Review of Dark Patterns Affecting Subscription Services and Privacy','url':'https://www.ftc.gov/news-events/news/press-releases/2024/07/ftc-icpen-gpen-announce-results-review-use-dark-patterns-affecting-subscription-services-privacy','date':'2024','use':'Observed prevalence of possible dark patterns in reviewed services.'},{'name':'Consumer Financial Protection Bureau','title':'How Do I Get My Money Back After an Unauthorized Transaction or Money Missing from My Bank Account?','url':'https://www.consumerfinance.gov/ask-cfpb/how-do-i-get-my-money-back-after-i-discover-an-unauthorized-transaction-or-money-missing-from-my-bank-account-en-1017/','date':'2023','use':'Starting point for unauthorized-transaction response.'},{'name':'Federal Trade Commission','title':'AI Companies: Uphold Your Privacy and Confidentiality Commitments','url':'https://www.ftc.gov/business-guidance/blog/2024/01/ai-companies-uphold-your-privacy-confidentiality-commitments','date':'2024','use':'Privacy commitments and changing data-use practices.'},{'name':'Consumer Financial Protection Bureau','title':'Advance Notice of Proposed Rulemaking: Personal Financial Data Rights Reconsideration','url':'https://files.consumerfinance.gov/f/documents/cfpb_personal-financial-data-rights-reconsideration_anpr_2025-08.pdf','date':'2025','use':'Current reconsideration and changing compliance timeline.'}],
'internal_links':[{'title':'Daily Yield Calculators','url':'https://dailyyield.blogspot.com/p/calculator_0908148622.html','relevance':'Recalculate savings and cash-flow effects independently.'},{'title':'Daily Yield Articles','url':'https://dailyyield.blogspot.com/p/daily-articles.html','relevance':'Continue with evidence-led money systems.'}],
'low_view_posts':json.load(open(R/'master_packages/rewrites/post_8372498042597820613.json'))['low_view_posts']}
out=R/'arena_work/post_2862470767911665544.json';out.write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n')
from master_article_v2 import validate
print(validate(P))
